### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by Couruuu** [neilccbrown/with-the-storm#1]
Hey there,

Just wanted to report a bug I'm experiencing. Save file at [Save.txt](https://github.com/neilccbrown/with-the-storm/files/13922506/Save.txt).

Failed to execute script 'main' due to unhandled exception: [WinError 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "main.py", line 236, in <module>
  File "watchdog\observers\api.py", line 261, in start
  File "watchdog\utils\__init__.py", line 92, in start
  File "watchdog\observers\read_directory_changes.py", line 59, in on_thread_start
  File "watchdog\observers\winapi.py", line 325, in get_directory_handle
  File "watchdog\observers\winapi.py", line 117, in _errcheck_handle
FileNotFoundError: [WinError 2] The system cannot find the file specified.

Complications that may be causing this:
- Running off E:/ drive rather than C:/
- Running off Xbox Gamepass rather than Steam

**Comment by neilccbrown** [comment]
Thanks for reporting this.  As a first step, in the newly released 1.0.7, I've added a button at the top of the window that lets you choose the location of the save file, so you can use that to find the "Save.save" file in wherever it is (you'll have to figure that out the first time, I'm afraid).  Once you find it, if you think the save file is in a relatively standard location that could be auto-detected, maybe add the path here and I'll put in code to automatically look there if it doesn't find it in the default that I've currently put in.
